INFO 2025-03-12 11:33:55,236 autoreload 38283 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:33:57,374 autoreload 38283 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-12 11:33:57,572 autoreload 38299 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:34:13,032 views 38299 6158004224 Attempting to fetch hackathons list
INFO 2025-03-12 11:34:13,032 views 38299 6158004224 Attempting to fetch hackathons list
INFO 2025-03-12 11:34:13,033 views 38299 6158004224 Cache miss for hackathons_list, querying database
INFO 2025-03-12 11:34:13,033 views 38299 6158004224 Cache miss for hackathons_list, querying database
ERROR 2025-03-12 11:34:13,038 views 38299 6158004224 Error fetching hackathons list: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py", line 53, in list
    logger.info(f"Successfully fetched {len(serializer.data)} hackathons")
                                            ^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 713, in to_representation
    return [
           ^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
ERROR 2025-03-12 11:34:13,038 views 38299 6158004224 Error fetching hackathons list: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py", line 53, in list
    logger.info(f"Successfully fetched {len(serializer.data)} hackathons")
                                            ^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 713, in to_representation
    return [
           ^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
ERROR 2025-03-12 11:34:13,062 log 38299 6158004224 Internal Server Error: /api/hackathons/
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py", line 53, in list
    logger.info(f"Successfully fetched {len(serializer.data)} hackathons")
                                            ^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 713, in to_representation
    return [
           ^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py", line 61, in list
    "detail": str(e) if settings.DEBUG else "Внутренняя ошибка сервера"
                        ^^^^^^^^
NameError: name 'settings' is not defined
INFO 2025-03-12 11:34:38,413 autoreload 38299 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py changed, reloading.
INFO 2025-03-12 11:34:38,800 autoreload 38499 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:34:39,938 autoreload 38499 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-12 11:34:40,255 autoreload 38503 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:34:40,485 views 38503 6131642368 Attempting to fetch hackathons list
INFO 2025-03-12 11:34:40,485 views 38503 6131642368 Attempting to fetch hackathons list
INFO 2025-03-12 11:34:40,485 views 38503 6131642368 Cache miss for hackathons_list, querying database
INFO 2025-03-12 11:34:40,485 views 38503 6131642368 Cache miss for hackathons_list, querying database
ERROR 2025-03-12 11:34:40,490 views 38503 6131642368 Error fetching hackathons list: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py", line 55, in list
    logger.info(f"Successfully fetched {len(serializer.data)} hackathons")
                                            ^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 713, in to_representation
    return [
           ^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
ERROR 2025-03-12 11:34:40,490 views 38503 6131642368 Error fetching hackathons list: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py", line 55, in list
    logger.info(f"Successfully fetched {len(serializer.data)} hackathons")
                                            ^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 713, in to_representation
    return [
           ^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
ERROR 2025-03-12 11:34:40,511 log 38503 6131642368 Internal Server Error: /api/hackathons/
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/renderers.py", line 658, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/renderers.py", line 565, in get_raw_data_form
    data = serializer.data.copy()
           ^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.get_initial()
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 421, in get_initial
    for field in self.fields.values()
                 ^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Hackathon` in `hackathon.serializers.HackathonSerializer`.
INFO 2025-03-12 11:35:00,770 autoreload 38503 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/urls.py changed, reloading.
INFO 2025-03-12 11:35:01,062 autoreload 38589 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:35:06,308 autoreload 38589 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-12 11:35:06,492 autoreload 38620 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:35:08,767 views 38620 6159888384 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:08,767 views 38620 6159888384 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:08,768 views 38620 6159888384 Cache miss for hackathons_list, querying database
INFO 2025-03-12 11:35:08,768 views 38620 6159888384 Cache miss for hackathons_list, querying database
INFO 2025-03-12 11:35:08,775 views 38620 6159888384 Successfully fetched 1 hackathons
INFO 2025-03-12 11:35:08,775 views 38620 6159888384 Successfully fetched 1 hackathons
INFO 2025-03-12 11:35:36,328 autoreload 38620 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-12 11:35:36,623 autoreload 38754 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:35:39,819 autoreload 38754 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py changed, reloading.
INFO 2025-03-12 11:35:40,010 autoreload 38769 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:35:45,257 views 38769 6166851584 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:45,257 views 38769 6166851584 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:45,257 views 38769 6166851584 Cache miss for hackathon queryset
INFO 2025-03-12 11:35:45,257 views 38769 6166851584 Cache miss for hackathon queryset
INFO 2025-03-12 11:35:45,261 views 38769 6166851584 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:35:45,261 views 38769 6166851584 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:35:45,743 views 38769 6166851584 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:45,743 views 38769 6166851584 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:45,748 views 38769 6166851584 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:35:45,748 views 38769 6166851584 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:35:46,093 views 38769 6166851584 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:46,093 views 38769 6166851584 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:46,098 views 38769 6166851584 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:35:46,098 views 38769 6166851584 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:35:57,014 views 38769 6166851584 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:57,014 views 38769 6166851584 Attempting to fetch hackathons list
INFO 2025-03-12 11:35:57,020 views 38769 6166851584 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:35:57,020 views 38769 6166851584 Successfully retrieved 1 hackathons
WARNING 2025-03-12 11:36:02,262 log 38769 6166851584 Not Found: /media/hackathons/ВТПО_Шаблон.png
INFO 2025-03-12 11:36:05,768 autoreload 38769 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-12 11:36:06,032 autoreload 38880 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:36:37,758 autoreload 38880 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-12 11:36:38,093 autoreload 39011 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 11:36:44,328 autoreload 39011 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-12 11:36:44,563 autoreload 39045 8346241088 Watching for file changes with StatReloader
WARNING 2025-03-12 11:36:45,642 log 39045 6135492608 Not Found: /media/hackathons/ВТПО_Шаблон.png
INFO 2025-03-12 11:36:47,901 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 11:36:47,901 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 11:36:47,902 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 11:36:47,902 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 11:36:47,913 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:36:47,913 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:36:57,569 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 11:36:57,569 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 11:36:57,579 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:36:57,579 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:40:30,604 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 11:40:30,604 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 11:40:30,619 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:40:30,619 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:46:14,449 views 39045 6152318976 Attempting to fetch hackathons list
INFO 2025-03-12 11:46:14,449 views 39045 6152318976 Attempting to fetch hackathons list
INFO 2025-03-12 11:46:14,449 views 39045 6152318976 Cache miss for hackathon queryset
INFO 2025-03-12 11:46:14,449 views 39045 6152318976 Cache miss for hackathon queryset
INFO 2025-03-12 11:46:14,479 views 39045 6152318976 Successfully retrieved 1 hackathons
INFO 2025-03-12 11:46:14,479 views 39045 6152318976 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:00:42,707 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 12:00:42,707 views 39045 6135492608 Cache miss for hackathon queryset
WARNING 2025-03-12 12:00:47,575 log 39045 6135492608 Method Not Allowed: /api/hackathons/1/register/
INFO 2025-03-12 12:11:07,961 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:11:07,961 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:11:07,963 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 12:11:07,963 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 12:11:07,987 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:11:07,987 views 39045 6135492608 Successfully retrieved 1 hackathons
WARNING 2025-03-12 12:11:39,122 log 39045 6135492608 Method Not Allowed: /api/hackathons/1/register/
INFO 2025-03-12 12:11:46,634 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:11:46,634 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:11:46,643 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:11:46,643 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:37:46,022 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:37:46,022 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:37:46,024 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 12:37:46,024 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 12:37:46,043 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:37:46,043 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:37:46,564 views 39045 6152318976 Attempting to fetch hackathons list
INFO 2025-03-12 12:37:46,564 views 39045 6152318976 Attempting to fetch hackathons list
INFO 2025-03-12 12:37:46,569 views 39045 6152318976 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:37:46,569 views 39045 6152318976 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:37:55,188 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:37:55,188 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:37:55,198 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:37:55,198 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:39:56,102 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:39:56,102 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 12:39:56,118 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 12:39:56,118 views 39045 6135492608 Successfully retrieved 1 hackathons
WARNING 2025-03-12 12:59:12,905 log 39045 6152318976 Not Found: /api/users/profile/
INFO 2025-03-12 13:09:45,650 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 13:09:45,650 views 39045 6135492608 Attempting to fetch hackathons list
INFO 2025-03-12 13:09:45,657 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 13:09:45,657 views 39045 6135492608 Cache miss for hackathon queryset
INFO 2025-03-12 13:09:45,674 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 13:09:45,674 views 39045 6135492608 Successfully retrieved 1 hackathons
INFO 2025-03-12 14:58:59,475 autoreload 39045 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/urls.py changed, reloading.
INFO 2025-03-12 14:58:59,948 autoreload 63223 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 14:59:20,406 autoreload 63223 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/models.py changed, reloading.
INFO 2025-03-12 14:59:20,686 autoreload 63330 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 15:02:01,249 autoreload 64076 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 16:33:37,335 autoreload 77613 8346241088 Watching for file changes with StatReloader
WARNING 2025-03-12 16:33:40,078 log 77613 6123237376 Not Found: /
WARNING 2025-03-12 16:33:47,418 log 77613 6123237376 Not Found: /api/users
WARNING 2025-03-12 16:33:53,306 log 77613 6123237376 Not Found: /api/users/
WARNING 2025-03-12 16:34:01,617 log 77613 6123237376 Forbidden: /api/users/auth/telegram/
WARNING 2025-03-12 16:34:13,905 log 77613 6123237376 Forbidden: /api/users/users/profile/
INFO 2025-03-12 16:37:32,540 autoreload 78804 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 18:19:28,006 autoreload 89661 8346241088 Watching for file changes with StatReloader
WARNING 2025-03-12 18:19:30,212 log 89661 6170701824 Not Found: /
WARNING 2025-03-12 18:19:36,600 log 89661 6170701824 Not Found: /api/users/
WARNING 2025-03-12 18:19:47,278 log 89661 6170701824 Forbidden: /api/users/users/profile/
INFO 2025-03-12 19:47:33,941 autoreload 9382 8346241088 Watching for file changes with StatReloader
WARNING 2025-03-12 19:47:35,756 log 9382 6159593472 Not Found: /api/auth/telegram/
WARNING 2025-03-12 19:49:24,366 log 9382 6159593472 Forbidden: /api/users/users/profile/
WARNING 2025-03-12 19:49:45,781 log 9382 6159593472 Forbidden: /api/users/users/profile/
WARNING 2025-03-12 19:52:08,732 log 9382 6159593472 Forbidden: /api/users/users/profile/
INFO 2025-03-12 19:52:28,596 autoreload 9382 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-12 19:52:28,978 autoreload 10712 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 19:52:30,165 autoreload 10712 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-12 19:52:30,423 autoreload 10715 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 20:06:55,185 autoreload 14155 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 20:08:20,191 autoreload 14155 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-12 20:08:20,575 autoreload 14474 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 20:08:33,953 autoreload 14474 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-12 20:08:34,237 autoreload 14530 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 20:08:48,023 views 14530 6128185344 Updated user with telegram_id: 5690145195
INFO 2025-03-12 20:14:51,857 autoreload 14530 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-12 20:14:52,237 autoreload 16030 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 20:15:04,661 autoreload 16030 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-12 20:15:04,992 autoreload 16087 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 20:15:19,389 autoreload 16087 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-12 20:15:19,653 autoreload 16164 8346241088 Watching for file changes with StatReloader
INFO 2025-03-12 20:16:00,675 autoreload 16164 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-12 20:16:01,007 autoreload 16328 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 08:52:43,065 autoreload 16328 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/asgiref/current_thread_executor.py changed, reloading.
INFO 2025-03-13 08:52:43,498 autoreload 74045 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 08:52:48,767 autoreload 74045 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/asgiref/current_thread_executor.py changed, reloading.
INFO 2025-03-13 08:52:49,013 autoreload 74077 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 09:17:00,708 autoreload 80201 8346241088 Watching for file changes with StatReloader
WARNING 2025-03-13 09:17:02,722 log 80201 6203437056 Not Found: /
INFO 2025-03-13 09:17:27,508 autoreload 80201 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/urls.py changed, reloading.
INFO 2025-03-13 09:17:27,817 autoreload 80317 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 09:17:36,140 autoreload 80317 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 09:17:36,452 autoreload 80361 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 09:17:50,547 views 80361 6201372672 Получен запрос на аутентификацию: {'telegram_id': '123456', 'username': 'test_user'}
ERROR 2025-03-13 09:17:50,551 views 80361 6201372672 Ошибка при аутентификации пользователя: UNIQUE constraint failed: users.username
ERROR 2025-03-13 09:17:50,552 log 80361 6201372672 Internal Server Error: /api/users/auth/telegram/
INFO 2025-03-13 09:18:04,229 autoreload 80361 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/models.py changed, reloading.
INFO 2025-03-13 09:18:04,513 autoreload 80501 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 09:18:11,751 autoreload 80501 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/models.py changed, reloading.
INFO 2025-03-13 09:18:12,044 autoreload 80542 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 10:57:16,327 autoreload 2764 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 10:59:32,783 autoreload 3360 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:08:12,707 autoreload 3360 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-13 11:08:13,025 autoreload 5499 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:08:46,994 autoreload 5499 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-13 11:08:47,306 autoreload 5647 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:10:06,177 autoreload 5647 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:10:06,511 autoreload 5967 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:10:09,749 autoreload 5967 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:10:09,937 autoreload 5981 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:11:10,539 autoreload 5981 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:11:10,887 autoreload 6195 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:11:16,105 autoreload 6195 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:11:16,395 autoreload 6229 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:11:27,694 autoreload 6229 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:11:27,995 autoreload 6294 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:11:33,224 autoreload 6294 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:11:33,450 autoreload 6323 8346241088 Watching for file changes with StatReloader
WARNING 2025-03-13 11:15:30,892 log 6323 6177091584 Unauthorized: /api/hackathons/
ERROR 2025-03-13 11:15:30,924 log 6323 6177091584 Internal Server Error: /api/auth/refresh/
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/serializers.py", line 116, in validate
    user := get_user_model().objects.get(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
WARNING 2025-03-13 11:16:53,496 log 6323 6160265216 Unauthorized: /api/hackathons/
ERROR 2025-03-13 11:16:53,581 log 6323 6160265216 Internal Server Error: /api/auth/refresh/
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/serializers.py", line 116, in validate
    user := get_user_model().objects.get(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
INFO 2025-03-13 11:17:49,178 views 6323 6160265216 Attempting to fetch hackathons list
INFO 2025-03-13 11:17:49,178 views 6323 6160265216 Attempting to fetch hackathons list
INFO 2025-03-13 11:17:49,180 views 6323 6160265216 Cache miss for hackathon queryset
INFO 2025-03-13 11:17:49,180 views 6323 6160265216 Cache miss for hackathon queryset
INFO 2025-03-13 11:17:49,186 views 6323 6160265216 Successfully retrieved 0 hackathons
INFO 2025-03-13 11:17:49,186 views 6323 6160265216 Successfully retrieved 0 hackathons
WARNING 2025-03-13 11:17:51,812 log 6323 6160265216 Unauthorized: /api/hackathons/
ERROR 2025-03-13 11:17:51,829 log 6323 6160265216 Internal Server Error: /api/auth/refresh/
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/serializers.py", line 116, in validate
    user := get_user_model().objects.get(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
INFO 2025-03-13 11:19:57,031 autoreload 6323 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:19:57,388 autoreload 8250 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:20:25,219 autoreload 8250 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-13 11:20:25,535 autoreload 8360 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:20:27,682 autoreload 8360 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-13 11:20:27,950 autoreload 8378 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:20:37,267 autoreload 8378 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/urls.py changed, reloading.
INFO 2025-03-13 11:20:37,469 autoreload 8415 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:21:08,412 autoreload 8415 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/urls.py changed, reloading.
INFO 2025-03-13 11:21:08,978 autoreload 8561 8346241088 Watching for file changes with StatReloader
ERROR 2025-03-13 11:21:11,972 log 8561 6200569856 Internal Server Error: /api/hackathons/
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'telegram_id' into field. Choices are: date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, user_permissions, username
INFO 2025-03-13 11:22:19,018 autoreload 8561 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py changed, reloading.
INFO 2025-03-13 11:22:19,385 autoreload 8820 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:22:47,322 autoreload 8820 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-13 11:22:47,645 autoreload 8933 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:26:10,785 autoreload 8933 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/views.py changed, reloading.
INFO 2025-03-13 11:26:11,154 autoreload 9708 8346241088 Watching for file changes with StatReloader
ERROR 2025-03-13 11:26:19,987 log 9708 6174175232 Internal Server Error: /api/auth/check/
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'telegram_id' into field. Choices are: date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, user_permissions, username
ERROR 2025-03-13 11:26:20,042 log 9708 6174175232 Internal Server Error: /api/hackathons/
Traceback (most recent call last):
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erkebulanmyrzabek/Desktop/timaloh/backend/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'telegram_id' into field. Choices are: date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, user_permissions, username
INFO 2025-03-13 11:27:17,131 autoreload 9708 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:27:17,507 autoreload 9973 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:27:47,363 autoreload 9973 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/users/views.py changed, reloading.
INFO 2025-03-13 11:27:47,686 autoreload 10102 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 11:29:10,270 autoreload 10102 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/backend/settings.py changed, reloading.
INFO 2025-03-13 11:29:10,905 autoreload 10380 8346241088 Watching for file changes with StatReloader
WARNING 2025-03-13 11:45:11,025 log 10380 6163804160 Unauthorized: /api/auth/check/
ERROR 2025-03-13 11:45:11,033 views 10380 6163804160 Error in CustomTokenRefreshView: User matching query does not exist.
ERROR 2025-03-13 11:45:11,033 log 10380 6163804160 Internal Server Error: /api/auth/refresh/
WARNING 2025-03-13 11:45:11,081 log 10380 6163804160 Unauthorized: /api/hackathons/
ERROR 2025-03-13 11:45:11,087 views 10380 6163804160 Error in CustomTokenRefreshView: User matching query does not exist.
ERROR 2025-03-13 11:45:11,087 log 10380 6163804160 Internal Server Error: /api/auth/refresh/
INFO 2025-03-13 12:23:41,199 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:23:41,199 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:23:41,201 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:23:41,201 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:23:41,212 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:23:41,212 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:10,796 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:10,796 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:10,798 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:10,798 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:13,293 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:13,293 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:13,294 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:13,294 views 10380 6163804160 Successfully retrieved 0 hackathons
WARNING 2025-03-13 12:24:13,319 log 10380 6180630528 Unauthorized: /api/hackathons/
ERROR 2025-03-13 12:24:13,325 views 10380 6180630528 Error in CustomTokenRefreshView: User matching query does not exist.
ERROR 2025-03-13 12:24:13,325 log 10380 6180630528 Internal Server Error: /api/auth/refresh/
INFO 2025-03-13 12:24:16,025 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:16,025 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:16,030 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:16,030 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:27,226 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:27,226 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:27,228 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:27,228 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:29,944 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:29,944 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:29,948 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:29,948 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:42,291 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:42,291 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:42,295 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:42,295 views 10380 6163804160 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:43,674 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:43,674 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:24:43,675 views 10380 6180630528 Successfully retrieved 0 hackathons
INFO 2025-03-13 12:24:43,675 views 10380 6180630528 Successfully retrieved 0 hackathons
WARNING 2025-03-13 12:24:58,378 log 10380 6163804160 Not Found: /
INFO 2025-03-13 12:30:11,296 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:30:11,296 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:30:11,298 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:30:11,298 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:30:11,304 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:30:11,304 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:11,581 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:11,581 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:11,583 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:36:11,583 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:36:11,598 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:11,598 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:26,332 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:26,332 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:26,337 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:26,337 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:26,859 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:26,859 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:26,861 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:26,861 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,062 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,062 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,063 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,063 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,217 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,217 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,218 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,218 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,412 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,412 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,412 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,412 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,586 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,586 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,587 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,587 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,759 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,759 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:36:27,760 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:36:27,760 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:36:31,607 log 10380 6163804160 Unauthorized: /api/
WARNING 2025-03-13 12:36:35,242 log 10380 6163804160 Unauthorized: /api/
WARNING 2025-03-13 12:36:39,815 log 10380 6163804160 Not Found: /
WARNING 2025-03-13 12:36:50,919 log 10380 6163804160 Not Found: /api/users/
WARNING 2025-03-13 12:40:33,309 log 10380 6180630528 Not Found: /auth/telegram/
WARNING 2025-03-13 12:40:35,825 log 10380 6163804160 Not Found: /auth/telegram/
WARNING 2025-03-13 12:42:28,569 log 10380 6163804160 Not Found: /hackathons/
INFO 2025-03-13 12:42:28,585 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:42:28,585 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:42:28,585 views 10380 6180630528 Cache miss for hackathon queryset
INFO 2025-03-13 12:42:28,585 views 10380 6180630528 Cache miss for hackathon queryset
INFO 2025-03-13 12:42:28,590 views 10380 6180630528 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:42:28,590 views 10380 6180630528 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:43:16,630 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:16,630 views 10380 6163804160 Attempting to fetch hackathons list
WARNING 2025-03-13 12:43:16,631 log 10380 6180630528 Bad Request: /api/auth/check/
INFO 2025-03-13 12:43:16,633 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:43:16,633 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:43:16,647 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:16,647 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:16,648 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:43:16,648 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:43:19,807 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:43:19,807 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:19,807 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:19,808 views 10380 6180630528 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:43:19,808 views 10380 6180630528 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:43:19,812 log 10380 6197456896 Bad Request: /api/auth/check/
INFO 2025-03-13 12:43:19,819 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:19,819 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:19,819 views 10380 6180630528 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:43:19,819 views 10380 6180630528 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:43:19,826 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:19,826 views 10380 6180630528 Attempting to fetch hackathons list
INFO 2025-03-13 12:43:19,826 views 10380 6180630528 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:43:19,826 views 10380 6180630528 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:44:58,178 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:44:58,206 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:44:58,206 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:44:58,209 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:44:58,209 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:45:14,536 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:45:14,536 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:45:14,537 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:45:14,537 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:46:02,887 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:46:02,929 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:46:02,929 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:46:02,930 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:46:02,930 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:48:00,987 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:48:01,008 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:01,008 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:01,008 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:48:01,008 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:48:01,010 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:01,010 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:15,700 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:15,700 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:15,703 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:15,703 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:19,637 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:19,637 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:19,638 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:19,638 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:29,182 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:29,182 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:29,183 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:29,183 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:29,565 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:29,565 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:29,565 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:29,565 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:30,070 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:30,070 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:30,071 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:30,071 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:33,236 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:33,236 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:33,236 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:33,236 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:33,521 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:33,521 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:33,522 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:33,522 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:34,136 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:34,136 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:34,136 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:34,136 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:35,011 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:35,011 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:35,012 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:35,012 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:37,001 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:37,001 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:37,002 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:37,002 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:38,977 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:38,977 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:48:38,977 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:48:38,977 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:50:14,355 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:14,355 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:14,356 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:50:14,356 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:50:15,331 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:50:15,345 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:15,345 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:15,346 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:50:15,346 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:50:16,295 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:50:16,326 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:16,326 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:16,326 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:50:16,326 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:50:16,879 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:50:16,902 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:16,902 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:16,902 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:50:16,902 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:50:17,064 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:50:17,101 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:17,101 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:17,102 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:50:17,102 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:50:17,237 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:50:17,261 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:17,261 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:50:17,262 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:50:17,262 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:52:46,113 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:52:46,159 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:52:46,159 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:52:46,161 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:52:46,161 views 10380 6163804160 Successfully retrieved 1 hackathons
WARNING 2025-03-13 12:52:51,122 log 10380 6163804160 Bad Request: /api/auth/check/
INFO 2025-03-13 12:52:51,136 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:52:51,136 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:52:51,136 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:52:51,136 views 10380 6163804160 Successfully retrieved 1 hackathons
INFO 2025-03-13 12:53:17,685 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:53:17,685 views 10380 6163804160 Attempting to fetch hackathons list
INFO 2025-03-13 12:53:17,687 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:53:17,687 views 10380 6163804160 Cache miss for hackathon queryset
INFO 2025-03-13 12:53:17,697 views 10380 6163804160 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:53:17,697 views 10380 6163804160 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:54:25,373 autoreload 10380 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-13 12:54:25,765 autoreload 21479 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 12:54:27,923 autoreload 21479 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-13 12:54:28,210 autoreload 21495 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 12:54:38,473 autoreload 21495 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-13 12:54:38,769 autoreload 21543 8346241088 Watching for file changes with StatReloader
INFO 2025-03-13 12:54:40,185 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:54:40,185 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:54:40,187 views 21543 6194999296 Cache miss for hackathon queryset
INFO 2025-03-13 12:54:40,187 views 21543 6194999296 Cache miss for hackathon queryset
INFO 2025-03-13 12:54:40,192 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:54:40,192 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:55:09,841 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:55:09,841 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:55:09,844 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:55:09,844 views 21543 6194999296 Successfully retrieved 2 hackathons
WARNING 2025-03-13 12:55:27,155 log 21543 6194999296 Bad Request: /api/auth/check/
INFO 2025-03-13 12:55:27,216 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:55:27,216 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:55:27,216 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:55:27,216 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:55:40,658 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:55:40,658 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:55:40,660 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:55:40,660 views 21543 6194999296 Successfully retrieved 2 hackathons
WARNING 2025-03-13 12:55:55,546 log 21543 6194999296 Bad Request: /api/auth/check/
WARNING 2025-03-13 12:57:12,068 log 21543 6194999296 Bad Request: /api/auth/check/
INFO 2025-03-13 12:57:12,496 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:57:12,496 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:57:12,499 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:57:12,499 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:57:25,893 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:57:25,893 views 21543 6194999296 Attempting to fetch hackathons list
INFO 2025-03-13 12:57:25,895 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:57:25,895 views 21543 6194999296 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:57:51,596 autoreload 21543 8346241088 /Users/erkebulanmyrzabek/Desktop/timaloh/backend/hackathon/serializers.py changed, reloading.
INFO 2025-03-13 12:57:52,028 autoreload 22360 8346241088 Watching for file changes with StatReloader
WARNING 2025-03-13 12:58:41,964 log 22360 6156955648 Bad Request: /api/auth/check/
INFO 2025-03-13 12:58:42,030 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 12:58:42,030 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 12:58:42,030 views 22360 6156955648 Cache miss for hackathon queryset
INFO 2025-03-13 12:58:42,030 views 22360 6156955648 Cache miss for hackathon queryset
INFO 2025-03-13 12:58:42,034 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:58:42,034 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:58:44,288 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 12:58:44,288 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 12:58:44,288 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:58:44,288 views 22360 6156955648 Successfully retrieved 2 hackathons
WARNING 2025-03-13 12:59:21,789 log 22360 6156955648 Bad Request: /api/auth/check/
INFO 2025-03-13 12:59:21,806 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 12:59:21,806 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 12:59:21,806 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:59:21,806 views 22360 6156955648 Successfully retrieved 2 hackathons
WARNING 2025-03-13 12:59:26,581 log 22360 6156955648 Bad Request: /api/auth/check/
INFO 2025-03-13 12:59:26,600 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 12:59:26,600 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 12:59:26,600 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 12:59:26,600 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 13:03:37,331 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 13:03:37,331 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 13:03:37,333 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 13:03:37,333 views 22360 6156955648 Successfully retrieved 2 hackathons
WARNING 2025-03-13 13:05:14,211 log 22360 6156955648 Bad Request: /api/auth/check/
INFO 2025-03-13 13:05:14,244 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 13:05:14,244 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 13:05:14,244 views 22360 6156955648 Cache miss for hackathon queryset
INFO 2025-03-13 13:05:14,244 views 22360 6156955648 Cache miss for hackathon queryset
INFO 2025-03-13 13:05:14,250 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 13:05:14,250 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 13:05:27,951 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 13:05:27,951 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 13:05:27,956 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 13:05:27,956 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 13:05:40,140 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 13:05:40,140 views 22360 6156955648 Attempting to fetch hackathons list
INFO 2025-03-13 13:05:40,141 views 22360 6156955648 Successfully retrieved 2 hackathons
INFO 2025-03-13 13:05:40,141 views 22360 6156955648 Successfully retrieved 2 hackathons
